### PR TITLE
Fixed 'eureka datacenter and environment not displayed on the dashboard'

### LINKED ISSUE #4032: Eureka datacenter and environment not displayed on the Eureka dashboard
I am using Eureka server - version 3.0.3 and have configured the datacenter and environment information using the below configuration:

```
eureka:
  datacenter: Mumbai
  environment: QA
  server:
    enable-self-preservation: false
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: false
    fetch-registry: false
```
I do not see the Datacenter and Environment information in the Eureka dashboard. In the older versions of Eureka, the information used to be displayed. Is there any change in the configuration with the current release?

### PR DESCRIPTION
**Pull request by weixsun**
Fixes #4032

### CODE REVIEW

File: spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java [hunk 1]
```diff
@@ -57,6 +58,9 @@
 
 	private ApplicationInfoManager applicationInfoManager;
 
+	@Autowired
+	private EurekaDeploymentProperties eurekaDeploymentProperties;
```
Comment (weixsun) [inline spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java:62]: The reason why constructor injection is not used is because I don’t want to break the existing test case code structure, and because I run the current test case, I found that there are some problems in the test case of this project. When these problems are solved, I very happy to use constructor injection and update relevant test code.

**Comment by OlgaMaciaszek** [comment]
Thanks, @weixsun - will take a look today.

File: spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaDeploymentProperties.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+import java.util.Objects;
+
+import org.springframework.boot.context.properties.ConfigurationProperties;
+
+/**
+ * Configuration properties for the Eureka deployment.
+ *
+ * @author Weix Sun
+ */
+@ConfigurationProperties("eureka")
```
Comment (OlgaMaciaszek) [inline spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaDeploymentProperties.java:28]: Please change the suffix to `eureka.deployment`.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Hello @weixsun, thanks for submitting the PR. In general, it looks good. However, please submit this PR against `3.1.x` branch instead of `main` so that this change is also included in the `2021.x` release train. Also, please add your full name with `@author` tag to any classes you've modified. Also, I have added some comments - please address them.

**Comment by OlgaMaciaszek** [comment]
Fixes gh-4032.

**Comment by weixsun** [comment]
@OlgaMaciaszek Thanks for the clear and effective code review, I resubmitted as requested.

File: spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java [hunk 3]
```diff
@@ -58,10 +59,19 @@ public class EurekaController {
 
 	private ApplicationInfoManager applicationInfoManager;
 
+	private EurekaDeploymentProperties eurekaDeploymentProperties;
```
Comment (OlgaMaciaszek) [inline spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java:62]: Let's add `final`. and set to `null` in the deprecated constructor.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Thanks @weixsun - it's nearly good to go -  we just need to be able to handle null `eurekaDeploymentProperties`; have added comments - please address them.

**Comment by weixsun** [comment]
@OlgaMaciaszek It's done.

File: spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaDeploymentProperties.java (hunk 2 above)
Comment (weixsun) [reply spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaDeploymentProperties.java]: Everyone has been using `eureka.environment` and `eureka.datacenter` for a long time, and now that we've changed the prefixes, should we remind everyone in the doc or in the release notes?

Comment (weixsun) [reply spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaDeploymentProperties.java]: > Please change the suffix to `eureka.deployment`.

Perhaps we can do the configuration item expiration specification in `spring-configuration-metadata.json` like Spring Boot and recommend the configuration item with the `eureka. deployment` prefix instead.

Is it worth it？😂

Comment (OlgaMaciaszek) [reply spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaDeploymentProperties.java]: You're right - sorry for the confusion, but given what  you've pointed out, I think we should switch it back to `eureka` prefix and then rename the class to `EurekaProperties` . We might want to do some additional work on all SC Netflix properties prefixes later on to ensure more consistency, but that will have to be done on the `main` branch.

File: spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java [hunk 4]
```diff
@@ -58,8 +59,17 @@ public class EurekaController {
 
 	private ApplicationInfoManager applicationInfoManager;
 
+	private final EurekaDeploymentProperties eurekaDeploymentProperties;
+
+	@Deprecated
```
Comment (OlgaMaciaszek) [inline spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java:64]: Let's also add a javadoc with `@deprecated in favour of `{@link ...}` tag.

File: spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaDeploymentProperties.java [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+import java.util.Objects;
+
+import org.springframework.boot.context.properties.ConfigurationProperties;
+
+/**
+ * Configuration properties for the Eureka deployment.
+ *
+ * @author Weix Sun
+ */
+@ConfigurationProperties("eureka.deployment")
```
Comment (OlgaMaciaszek) [inline spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaDeploymentProperties.java:28]: Let's switch as described in this comment: https://github.com/spring-cloud/spring-cloud-netflix/pull/4086#discussion_r849338707 - I'm sorry for asking you to change it twice, but you're right here.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
@weixsun have added 2 more comments - please take a look.

File: spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaDeploymentProperties.java (hunk 2 above)
Comment (weixsun) [reply spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaDeploymentProperties.java]: > I think we should switch it back to `eureka`prefix and then rename the class to `EurekaProperties`

Ok, Let me do a quick fix

**Review by OlgaMaciaszek — APPROVED** [review]
LGTM
