### PR TITLE
Return content of last request when retrying failed requests

### LINKED ISSUE #2353: Cannot get response content while using retry in zuul
If the response from server has the status code configured in ribbon.retryableStatusCodes, the response content will be changed and I cannot get the origin response content from zuul which is usually necessary for my application.
Will this be fixed in the future?

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Some code taken from #2592.  Fixes #2353.

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@lly5044 would appreciate your review

**Comment by lly5044** [comment]
I didn't do a test , but I think you haven't extracted the content of response before you close the connection.
Could you get the content later after you retry failed?
In HttpClientStatusCodeException And RibbonResponseStatusCodeException 
@ryanjbaxter

**Comment by ryanjbaxter** [comment]
@lly5044 thanks for catching that!

**Comment by ryanjbaxter** [comment]
@lly5044 is you could take a look at the related PR in Commons as well that would be great https://github.com/spring-cloud/spring-cloud-commons/pull/309

File: spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/okhttp/OkHttpStatusCodeException.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+	private Response response;
+
+	public OkHttpStatusCodeException(String serviceId, Response response, URI uri) throws IOException {
+		super(serviceId, response.code(), response, uri);
+		this.response = new Response.Builder().code(response.code()).message(response.message()).protocol(response.protocol())
+				.request(response.request()).headers(response.headers()).handshake(response.handshake())
+				.cacheResponse(response.cacheResponse()).networkResponse(response.networkResponse())
+				.priorResponse(response.priorResponse()).sentRequestAtMillis(response.sentRequestAtMillis())
+				.body(response.peekBody(Integer.MAX_VALUE)).build();
+		response.close();
```
Comment (spencergibb) [inline spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/okhttp/OkHttpStatusCodeException.java]: Moving this here seems very strange to me.

Comment (ryanjbaxter) [reply spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/okhttp/OkHttpStatusCodeException.java]: Since the exception(s) were actually reading in the response, it seemed to make sense to me that it would be responsible for closing the response as well.  I suppose we can move it outside of the constructor, it just seemed disconnected that way.

Comment (ryanjbaxter) [reply spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/okhttp/OkHttpStatusCodeException.java]: wrapping all this logic about copying over the response body in the exception also seemed to simplify the code in load balancing clients.  if we were to move the close call back to the load balancing clients than we would also have to move the code that copies the response body back there as well and it just added to something that was already complex.  since the fallback was using the response from the exception it just seemed to make the most sense to me to keep all that logic in the exception itself.

**Comment by spencergibb** [comment]
Ok, maybe the class shouldn't be an exception, but something that returns one? Having that kind of logic in an exception feels wrong to me.

**Comment by ryanjbaxter** [comment]
@spencergibb think this is a good compromise, let me know what you think
