### PR TITLE
Fix circular dependency in ZuulProxyAutoConfiguration

### LINKED ISSUE #3733: ZuulProxyAutoConfiguration forms a circular dependency with itself
`ZuulProxyAutoConfiguration` requires:
```
@Autowired
private ServiceRouteMapper serviceRouteMapper;
```
and defines it at the same time:
```
@Bean
@ConditionalOnMissingBean(ServiceRouteMapper.class)
public ServiceRouteMapper serviceRouteMapper() {
	return new SimpleServiceRouteMapper();
}
```
this makes application start up fail, when circular references are disabled (`org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.setAllowCircularReferences(false)`).

### PR DESCRIPTION
**Pull request by ewirch**
ZuulProxyAutoConfiguration declared a ServiceRouteMapper bean and required it for a field injection at the same time. Fixes #3733.

### CODE REVIEW

File: spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/ZuulProxyAutoConfiguration.java [hunk 1]
```diff
@@ -86,10 +83,9 @@ public HasFeatures zuulFeature() {
 
 	@Bean
 	@ConditionalOnMissingBean(DiscoveryClientRouteLocator.class)
-	public DiscoveryClientRouteLocator discoveryRouteLocator() {
+	public DiscoveryClientRouteLocator discoveryRouteLocator(ServiceRouteMapper serviceRouteMapper) {
 		return new DiscoveryClientRouteLocator(this.server.getServlet().getContextPath(),
-				this.discovery, this.zuulProperties, this.serviceRouteMapper,
```
Comment (spencergibb) [inline spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/ZuulProxyAutoConfiguration.java:91]: Why did you remove it from the constructor?

Comment (ewirch) [reply spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/ZuulProxyAutoConfiguration.java:91]: You're a fast one. ;) It's still a draft PR.

**Comment by ewirch** [comment]
Tests pass. But codecov/project doesn't like the change. :thinking:

**Comment by spencergibb** [comment]
Don't worry about that.
