### PR TITLE
fixes permanently down after refresh

### LINKED ISSUE #2972: Eureka client permanently down after refresh
Issue most likely related to several, but I want emphasize the root problem here (IMHO).
The very last issue that I've found is https://github.com/spring-cloud/spring-cloud-netflix/issues/1857 .

**Pre-requirements:**
cloud version - `Edgware.SR3`
1. setup simplest eureka server
2. setup simplest boot app only with eureka-client dep 
with properties `eureka.instance.initialStatus=DOWN` and `eureka.client.healthcheck.enabled=true`

**Steps to reproduce:**
1. Start service 
- Service registers in eureka with `DOWN` status, since it is initial status.
- `InstanceInfoReplicator` updates status to `UP` as it now uses `EurekaHealthCheckHandler` which was registered by `EurekaAutoServiceRegistration`, but not going to `InstanceInfo` object to get current `DOWN` state
2. Calling /refresh endpoint
- `CloudEurekaClient` bean recreated and re-registers instance in Eureka with initial status `DOWN`
- `InstanceInfoReplicator` keeping re-registering instance with `DOWN` status as it uses empty `HealthCheckCallbackToHandlerBridge` which gets current `DOWN` state from  `InstanceInfo`, but not from `EurekaAutoServiceRegistration`, from which it should.

**Root cause:**
`EurekaHealthCheckHandler` uses `EurekaRegistration` bean as provider for `EurekaClient` object.
Since it's not being recreated it stores old `CloudEurekaClient` and `EurekaHealthCheckHandler` sets to inactive bean (which was dropped of spring context due to refresh scope) instead of newly created one.
It can be easily seen in debug mode, it shows different objects hashcodes in spring context and in `EurekaRegistration` bean.
It actually was the root cause of https://github.com/Netflix/eureka/issues/1025 since it tried to call `onDemandUpdate` on shut down client.

**Possible solutions:**
- Make `EurekaRegistration` bean refresh scoped and use bean `Provider` in `EurekaAutoServiceRegistration` to retrieve bean from context after refresh
- Rewrite `EurekaRegistration.getEurekaClient()` to get `CloudEurekaClient` bean from context, not cached one.

**Why does it actually that matter?**
This issue was possible to find only using `eureka.instance.initialStatus=DOWN` property, but in case of default `UP` you won't be able to see, that after refresh (manual/bus) service won't be `DOWN` anymore, even if some health indicators will go `DOWN`.

### PR DESCRIPTION
**Pull request by tdanylchuk**
root cause:
cached bean trying to re-register
resolution summary:
get re-created bean from context to re-register

Fixes #2972

### CODE REVIEW

File: spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaAutoServiceRegistration.java [hunk 1]
```diff
@@ -52,41 +54,44 @@
 
 	private EurekaServiceRegistry serviceRegistry;
 
-	private EurekaRegistration registration;
+	private ObjectProvider<EurekaRegistration> registrationProvider;
```
Comment (spencergibb) [inline spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaAutoServiceRegistration.java]: Did you try without object provider? Refresh scope creates a proxy which should handle getting the refreshed instance for you.

**Comment by tdanylchuk** [comment]
I'll port fix to master soon

File: spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaRegistration.java [hunk 2]
```diff
@@ -201,8 +201,4 @@ public int getSecurePort() {
 		return this.instanceConfig.getSecurePort();
 	}
 
-	@Override
-	public void close() throws IOException {
```
Comment (spencergibb) [inline spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaRegistration.java]: I worry that this will have negative sure effects: it won't deregister on a normal shutdown.

File: spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfigurationTests.java [hunk 3]
```diff
@@ -425,16 +466,6 @@ public void eurekaClientClosed() {
 		}
 	}
 
-	@Test
-	public void eurekaRegistrationClosed() throws IOException {
```
Comment (spencergibb) [inline spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfigurationTests.java]: This test can't be removed as it is a regression

**Comment by spencergibb** [comment]
Don't port, we merge forward if accepted.

File: spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaRegistration.java (hunk 2 above)
Comment (tdanylchuk) [reply spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaRegistration.java]: since `DiscoveryClient` is bean itself with marked destroy method, I don't think we need close it twice.
BTW saw exception in logs related this before Egware.3 (when exception was thrown but not muted)

Anyway I've wrote test for this, you may take a look.

File: spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfigurationTests.java (hunk 3 above)
Comment (tdanylchuk) [reply spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfigurationTests.java]: test is being moved to ```shouldCloseDiscoveryClient``` since `EurekaRegistration` is not closing DiscoveryClient anymore

File: spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaAutoServiceRegistration.java (hunk 1 above)
Comment (tdanylchuk) [reply spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaAutoServiceRegistration.java]: Khmm, will try, was thinking only about lazy init as proxy, but not refreshed bean

Comment (tdanylchuk) [reply spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaAutoServiceRegistration.java]: works, fine, reverted class change

**Comment by tdanylchuk** [comment]
can't get why it's failing, locally works well and changes should not affect test functionality which is failing...

File: spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaRegistration.java (hunk 2 above)
Comment (ryanjbaxter) [reply spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaRegistration.java]: So where will we shutdown the client otherwise?

Comment (tdanylchuk) [reply spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaRegistration.java]: we don't , spring context will shutdown it for us
```
@Bean(destroyMethod = "shutdown")
@ConditionalOnMissingBean(value = EurekaClient.class, search = SearchStrategy.CURRENT)
public EurekaClient eurekaClient(ApplicationInfoManager manager, EurekaClientConfig config) {
	return new CloudEurekaClient(manager, config, this.optionalArgs, this.context);
}
```
Here is shutdown method `@Bean(destroyMethod = "shutdown")`

Comment (ryanjbaxter) [reply spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaRegistration.java]: got it thanks

**Comment by tdanylchuk** [comment]
@ryanjbaxter can we port it to master branch?

**Comment by ryanjbaxter** [comment]
I merged it forward, you might want to double check the merge because it wasnt pretty.  All the tests were passing for me locally.

**Comment by tdanylchuk** [comment]
I see some unrelated changes to my PR at https://github.com/spring-cloud/spring-cloud-netflix/commit/13c2500d0ea77734223f3bcac4bdf0863a0fd3b5 - you want me to polish them?

**Comment by ryanjbaxter** [comment]
The unrelated changes are coming from other PRs that were merged forward
